version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartmail-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartmail
      POSTGRES_USER: smartmail
      POSTGRES_PASSWORD: smartmail
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: smartmail-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
